### ISSUE TITLE
Input bar overlaps in the screen

### ISSUE THREAD

**Issue by priyanshtiwari001** [siiddhantt/tts-playground#2]
Hi @siiddhantt , I found a bug in your website. When we tried to type our name in the input box. our name get overlaps inside the screen please.
<img width="1096" alt="Screenshot 2023-10-12 at 6 41 59 PM" src="https://github.com/siiddhantt/tts-playground/assets/64392162/463e16ed-e3f9-4cc2-aaca-aaacd2032b61">

I would like to resolve this issue. Kindly please assign me this under the hacktoberfest or hacktoberfest-accepted label

**Comment by siiddhantt** [comment]
Sure, you can work on this. I've assigned you the issue.

**Comment by priyanshtiwari001** [comment]
AS I participated in Hacktoberfest program, Can you please add the **hacktoberfest label** in this issue. It will be help me . Thanks for understanding

**Comment by siiddhantt** [comment]
I have added it now, thanks for reminding me.

**Comment by priyanshtiwari001** [comment]
hi @siiddhantt  , here are the changes I added.
<img width="727" alt="Screenshot 2023-10-13 at 8 53 19 PM" src="https://github.com/siiddhantt/tts-playground/assets/64392162/c8c41a7c-8845-433a-b974-e1e95e5d93f2">

**Comment by priyanshtiwari001** [comment]
Hi @siiddhantt, kindly please review the commit changes. thank you
